### ISSUE TITLE
Document the code?

### ISSUE THREAD

**Issue by Khhs167** [RedCubeDev-ByteSpace/CCScripts#1]
My man red out here open sourcing his mc smp code, i approve, but there is a lack of comments in the code.

**Comment by RedCubeDev-ByteSpace** [comment]
lmao didnt think anyone would ever find this repo

**Comment by Khhs167** [comment]
Well, fun fact; You got a follower!

Den mån 30 maj 2022 kl 12:32 skrev RedCubeDev ***@***.***>:

**Comment by Khhs167** [comment]
I'll close this as i take that as a no.
